name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: macos-latest
    steps:
      - name: Flutter Check
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'
          channel: 'stable'
          architecture: x64
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub publish --dry-run
#      - run: flutter pub publish --force

      - name: Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Change directory to example & Create Android Demo App
        working-directory: ./example
        run: flutter build apk